version: '3.8'

services:
  database:
    image: mongo:latest
    container_name: mongodb
    hostname: database
    networks:
      - nebulous

  bot:
    image: ghcr.io/tymonmarek/nebulous:latest
    container_name: bot
    environment:
      - DISCORD_TOKEN=YOUR_DISCORD_TOKEN
    depends_on:
      - mongodb
    networks:
      - nebulous

networks:
  nebulous:
    driver: bridge
