version: "3.8"

services:
    database:
        image: mongo:latest
        container_name: mongodb
        hostname: database
        networks:
            - nebulous

    bot:
        image: ghcr.io/tymonmarek/nebulous:latest
        container_name: bot
        environment:
            - DISCORD_TOKEN=${DISCORD_TOKEN}
        depends_on:
            - database
        networks:
            - nebulous

networks:
    nebulous:
        driver: bridge
